import Main from "@/components/Main"
import './globals.css'

export const metadata = {
  title: 'Next.js',
  description: 'Generated by Next.js',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body>
        <Main hello={'sdfsdf'}>
          {children}
        </Main>
      </body>
    </html>
  )
}
